<?php

namespace AlterEgoBundle\Repository;

/**
 * CreneauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDispo() {
        $now = new \DateTime();
        return $this->createQueryBuilder('c')
            ->where('c.dateheure > :now')
                ->setParameter('now', $now->format('Y-m-d H:i:s'))
            ->andWhere('c.placerestantes > :placeRestante')
                ->setParameter('placeRestante', 0)
            ->getQuery()->getResult();

    }
}