<?php
/**
 * Created by PhpStorm.
 * User: quentin
 * Date: 18/01/17
 * Time: 14:25
 */

namespace AlterEgoBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

}