<?php

namespace AlterEgoBundle\Repository;

/**
 * InfoEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
