<?php

namespace AlterEgoBundle\Repository;

/**
 * InfosEmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosEmployeRepository extends \Doctrine\ORM\EntityRepository
{
}
