<?php

namespace AlterEgoBundle\Repository;
use Application\Sonata\UserBundle\Entity\User;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
