<?php

namespace AlterEgoBundle\Repository;

/**
 * TestPerfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestPerfRepository extends \Doctrine\ORM\EntityRepository
{
}
