# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.admin.terrain:
            class: AlterEgoBundle\Admin\EntrepriseAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Client", label: "Entreprise" }
            arguments:
                - ~
                - AlterEgoBundle\Entity\Entreprise
                - ~