services:

  redirect.after.login:
    class: AlterEgoBundle\Redirection\AfterLoginRedirection
    arguments: [@router]

  redirect.after.logout:
    class: AlterEgoBundle\Redirection\AfterLogoutRedirection
    arguments: [@router, @security.context]